---
title: "p8105_hw6_wm2473"
output: github_document
date: "2022-11-26"
---

```{r}
library(tidyverse)
library(readxl)
library(rvest)
library(modelr)
library(corrplot)
library(ggplot2)
set.seed(1)
```

```{r}
hd = read_csv("homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city,",", state), 
         homicides = case_when(disposition == "Closed without arrest" ~ "unsolved homicides", disposition == "Open/No arrest" ~ "unsolved homicides", disposition == "Closed by arrest" ~ "solved homicides"), victim_age = as.numeric(victim_age), homicides = as.factor(homicides)) %>% 
    filter(!city_state %in% c("Tulsa,AL","Dallas,TX", "Phoenix,AZ", "Kansas City,MO"),victim_race %in% c("Black","White")) %>% 
  relocate(city_state)
```

obtain the estimate and confidence interval 
```{r}
md = hd %>% 
  filter(city_state %in% "Baltimore,MD") 
fit_1 = glm(homicides ~ victim_age+ victim_sex+ victim_race, data =md, family= binomial()) 
broom::tidy(fit_1)

tidy = fit_1 %>% 
  broom::tidy() %>% 
   mutate(OR = exp(estimate), lower = exp(estimate - 1.96*std.error), upper = exp(estimate + 1.96*std.error)) %>% 
  filter(term %in% "victim_sexMale") %>% 
  select(term, OR, lower, upper)
```


```{r}
city_odds_ci = function(city_df){
  fit_test = glm(homicides ~ victim_age + victim_sex + victim_race, data =city_df, family= binomial())  
    male_vs_female = filter(broom::tidy(fit_test), term == "victim_sexMale") %>% 
    mutate(OR = exp(estimate), lower = exp(estimate - 1.96*std.error), upper = exp(estimate + 1.96*std.error))
    
  return(male_vs_female)
  }
```

```{r}
nested_df = hd %>%
  nest(alldata = uid:homicides) %>% 
  mutate(
    test_results = map(alldata, city_odds_ci)
  ) %>% 
  select(city_state, test_results) %>% 
  unnest(test_results) %>% 
select(city_state, OR, lower, upper)
```

Creat a plot
```{r}
nested_df %>%
  mutate(city_state = fct_reorder(city_state, OR)) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "City Estimation",
       x = "City_State",
       y = "Estimate") 
```


Problem 3
```{r}
bw = read_csv("birthweight.csv") %>% 
  janitor::clean_names() %>% 
   mutate(babysex = as.factor(babysex),frace = as.factor(frace),malform = as.factor(malform), mrace = as.factor(mrace)) 
sum(is.na(bw)) ## make sure that there is no missing value
```



```{r}
bw %>%
  select(-babysex,-frace,-malform,-mrace,-pnumlbw,-pnumsga) %>%
  cor(method = "pearson") %>%
  corrplot(
    method = "color",
    type = "lower",
    tl.col = "Black",
    tl.srt = 45,
    diag = F,
    order = "AOE"
  )
```


```{r}
fit_bwt = lm(bwt ~ blength + bhead, data = bw) 

fit_bwt %>%   
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

```{r}
bw %>%
  modelr::add_residuals(fit_bwt) %>%
  modelr::add_predictions(fit_bwt) %>%
  ggplot(aes(x = pred, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0,
             col = "red",
             linetype = "dashed") +
  geom_smooth(method = "loess") +
  labs(title = "Residual vs Fitted Plot",
       x = "Fitted values",
       y = "Residuals") +
  theme(plot.title = element_text(hjust = 0.5))
```

Compare your model to two others:
```{r}
cv = modelr::crossv_mc(bw, 100) 
cv_df %>%
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble)) %>%
  mutate(
    mod_blength_bhead = map(train, ~ lm(bwt ~ blength + bhead, data = .x)),
    mod_blength_gaweeks = map(train, ~ lm(bwt ~ blength + gaweeks, data = .x)),
    mod_bheaed_blength_sex = map(
      train,
      ~ lm(bwt ~ babysex + bhead + blength + babysex * bhead + 
          babysex * blength + bhead * blength + 
          babysex * bhead * blength,data = .x))
  ) %>%  
mutate(
    rmse_blength_bhead = map2_dbl(mod_blength_bhead, test, ~ rmse(model = .x, data = .y)),
    rmse_blength_gaweeks = map2_dbl(mod_blength_gaweeks, test, ~ rmse(model = .x, data = .y)),
    rmse_bheaed_blength_sex = map2_dbl(mod_bheaed_blength_sex, test, ~ rmse(model = .x, data = .y))) %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_")
```

